//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Library.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Library.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   attribute &apos;{0}&apos; already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AttributeAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_AttributeAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   attribute &apos;{0}&apos; does not exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AttributeDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_AttributeDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot convert &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotConvert_Format {
            get {
                return ResourceManager.GetString("Exception_CannotConvert_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   command &apos;{0}&apos; already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CommandAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_CommandAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   command &apos;{0}&apos; does not exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CommandDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_CommandDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delimiter must be a Punctuation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_DelimiterMustBePunctuation {
            get {
                return ResourceManager.GetString("Exception_DelimiterMustBePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty strings are not allowed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_EmptyStringsAreNotAllowed {
            get {
                return ResourceManager.GetString("Exception_EmptyStringsAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid argument type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidArgumentType {
            get {
                return ResourceManager.GetString("Exception_InvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is invalid command name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidCommandName_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidCommandName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is invalid value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidValue_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   member &apos;{0}&apos; does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_MemberDoesNotExist_Format {
            get {
                return ResourceManager.GetString("Exception_MemberDoesNotExist_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   method &apos;{0}&apos; does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_MethodDoesNotExist_Format {
            get {
                return ResourceManager.GetString("Exception_MethodDoesNotExist_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name &apos;{0}&apos; already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NameAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_NameAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name &apos;{0}&apos; does not exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NameDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_NameDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name length must be greater than 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NameLengthMustBeGreaterThanOne {
            get {
                return ResourceManager.GetString("Exception_NameLengthMustBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not property.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotProperty_Format {
            get {
                return ResourceManager.GetString("Exception_NotProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   property &apos;{0}&apos; already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_PropertyAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_PropertyAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   property &apos;{0}&apos; can not use.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_PropertyCannotUse_Format {
            get {
                return ResourceManager.GetString("Exception_PropertyCannotUse_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   property &apos;{0}&apos; does not exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_PropertyDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_PropertyDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shortName must be a alphabet character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ShortNameMustBe_AlphabetCharacter {
            get {
                return ResourceManager.GetString("Exception_ShortNameMustBe_AlphabetCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; can not use. property &apos;{1}&apos; value must be &apos;{2}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Trigger_CannotUseProperty_Format {
            get {
                return ResourceManager.GetString("Exception_Trigger_CannotUseProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; can not use. property &apos;{1}&apos; value must be not &apos;{2}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Trigger_CannotUsePropertyNot_Format {
            get {
                return ResourceManager.GetString("Exception_Trigger_CannotUsePropertyNot_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type is not static class과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_TypeIsNotStaticClass {
            get {
                return ResourceManager.GetString("Exception_TypeIsNotStaticClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value of &apos;{0}&apos; is not set.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ValudIsNotSet_Format {
            get {
                return ResourceManager.GetString("Exception_ValudIsNotSet_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; cannot be used as multiple.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_VariablesCannotBeUsedAsMultiple_Format {
            get {
                return ResourceManager.GetString("Exception_VariablesCannotBeUsedAsMultiple_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; property must be an array type.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_VariablesPropertyMustBeAnArrayType_Format {
            get {
                return ResourceManager.GetString("Exception_VariablesPropertyMustBeAnArrayType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type &apos;{0}&apos; for usage.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Help_Format {
            get {
                return ResourceManager.GetString("Message_Help_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type &apos;{0}&apos; for version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Version_Format {
            get {
                return ResourceManager.GetString("Message_Version_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available commands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_AvaliableCommands {
            get {
                return ResourceManager.GetString("Text_AvaliableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Options {
            get {
                return ResourceManager.GetString("Text_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requirements과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Requirements {
            get {
                return ResourceManager.GetString("Text_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subcommands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Subcommands {
            get {
                return ResourceManager.GetString("Text_Subcommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Summary {
            get {
                return ResourceManager.GetString("Text_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Usage {
            get {
                return ResourceManager.GetString("Text_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Text_Variables {
            get {
                return ResourceManager.GetString("Text_Variables", resourceCulture);
            }
        }
    }
}
