//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.Library.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.Library.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute &apos;{0}&apos; already exists..
        /// </summary>
        public static string Exception_AttributeAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_AttributeAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute &apos;{0}&apos; does not exists..
        /// </summary>
        public static string Exception_AttributeDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_AttributeDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;BufferWidth&apos; can only be set when the &apos;Console.IsOutputRedirect&apos; value is true..
        /// </summary>
        public static string Exception_BufferWidthCannotSet {
            get {
                return ResourceManager.GetString("Exception_BufferWidthCannotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert &apos;{0}&apos;..
        /// </summary>
        public static string Exception_CannotConvert_Format {
            get {
                return ResourceManager.GetString("Exception_CannotConvert_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command &apos;{0}&apos; already exists..
        /// </summary>
        public static string Exception_CommandAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_CommandAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command &apos;{0}&apos; does not exists..
        /// </summary>
        public static string Exception_CommandDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_CommandDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter must be a Punctuation..
        /// </summary>
        public static string Exception_DelimiterMustBePunctuation {
            get {
                return ResourceManager.GetString("Exception_DelimiterMustBePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty strings are not allowed..
        /// </summary>
        public static string Exception_EmptyStringsAreNotAllowed {
            get {
                return ResourceManager.GetString("Exception_EmptyStringsAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument type..
        /// </summary>
        public static string Exception_InvalidArgumentType {
            get {
                return ResourceManager.GetString("Exception_InvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid command name..
        /// </summary>
        public static string Exception_InvalidCommandName_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidCommandName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid value..
        /// </summary>
        public static string Exception_InvalidValue_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous use in Invoke can pose a risk. Use InvokeAsync instead..
        /// </summary>
        public static string Exception_InvokeAsyncInstead {
            get {
                return ResourceManager.GetString("Exception_InvokeAsyncInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member &apos;{0}&apos; does not exist..
        /// </summary>
        public static string Exception_MemberDoesNotExist_Format {
            get {
                return ResourceManager.GetString("Exception_MemberDoesNotExist_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method &apos;{0}&apos; does not exist..
        /// </summary>
        public static string Exception_MethodDoesNotExist_Format {
            get {
                return ResourceManager.GetString("Exception_MethodDoesNotExist_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name &apos;{0}&apos; already exists..
        /// </summary>
        public static string Exception_NameAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_NameAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name &apos;{0}&apos; does not exists..
        /// </summary>
        public static string Exception_NameDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_NameDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name length must be greater than 1..
        /// </summary>
        public static string Exception_NameLengthMustBeGreaterThanOne {
            get {
                return ResourceManager.GetString("Exception_NameLengthMustBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not property..
        /// </summary>
        public static string Exception_NotProperty_Format {
            get {
                return ResourceManager.GetString("Exception_NotProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the bool type can be used as a switch..
        /// </summary>
        public static string Exception_OnlyBoolTypeSwitch {
            get {
                return ResourceManager.GetString("Exception_OnlyBoolTypeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt cannot be set while reading a string..
        /// </summary>
        public static string Exception_PromptCannotSet {
            get {
                return ResourceManager.GetString("Exception_PromptCannotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property &apos;{0}&apos; already exists..
        /// </summary>
        public static string Exception_PropertyAlreadyExists_Format {
            get {
                return ResourceManager.GetString("Exception_PropertyAlreadyExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property &apos;{0}&apos; can not use..
        /// </summary>
        public static string Exception_PropertyCannotUse_Format {
            get {
                return ResourceManager.GetString("Exception_PropertyCannotUse_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property &apos;{0}&apos; does not exists..
        /// </summary>
        public static string Exception_PropertyDoesNotExists_Format {
            get {
                return ResourceManager.GetString("Exception_PropertyDoesNotExists_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadLine operation canceled..
        /// </summary>
        public static string Exception_ReadOnlyCanceled {
            get {
                return ResourceManager.GetString("Exception_ReadOnlyCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortName must be a alphabet character..
        /// </summary>
        public static string Exception_ShortNameMustBe_AlphabetCharacter {
            get {
                return ResourceManager.GetString("Exception_ShortNameMustBe_AlphabetCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can not use. property &apos;{1}&apos; value must be &apos;{2}&apos;..
        /// </summary>
        public static string Exception_Trigger_CannotUseProperty_Format {
            get {
                return ResourceManager.GetString("Exception_Trigger_CannotUseProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; can not use. property &apos;{1}&apos; value must be not &apos;{2}&apos;..
        /// </summary>
        public static string Exception_Trigger_CannotUsePropertyNot_Format {
            get {
                return ResourceManager.GetString("Exception_Trigger_CannotUsePropertyNot_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type is not static class..
        /// </summary>
        public static string Exception_TypeIsNotStaticClass {
            get {
                return ResourceManager.GetString("Exception_TypeIsNotStaticClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not identify version..
        /// </summary>
        public static string Exception_UnknownVersion {
            get {
                return ResourceManager.GetString("Exception_UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &apos;{0}&apos; is not set..
        /// </summary>
        public static string Exception_ValudIsNotSet_Format {
            get {
                return ResourceManager.GetString("Exception_ValudIsNotSet_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be used as multiple..
        /// </summary>
        public static string Exception_VariablesCannotBeUsedAsMultiple_Format {
            get {
                return ResourceManager.GetString("Exception_VariablesCannotBeUsedAsMultiple_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property must be an array type..
        /// </summary>
        public static string Exception_VariablesPropertyMustBeAnArrayType_Format {
            get {
                return ResourceManager.GetString("Exception_VariablesPropertyMustBeAnArrayType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; for usage..
        /// </summary>
        public static string Message_Help_Format {
            get {
                return ResourceManager.GetString("Message_Help_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0} {1}&apos; for usage..
        /// </summary>
        public static string Message_HelpUsage_Format {
            get {
                return ResourceManager.GetString("Message_HelpUsage_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unprocessed arguments..
        /// </summary>
        public static string Message_UnprocessedArguments {
            get {
                return ResourceManager.GetString("Message_UnprocessedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; for version..
        /// </summary>
        public static string Message_Version_Format {
            get {
                return ResourceManager.GetString("Message_Version_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands.
        /// </summary>
        public static string Text_AvaliableCommands {
            get {
                return ResourceManager.GetString("Text_AvaliableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Text_Description {
            get {
                return ResourceManager.GetString("Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Text_Example {
            get {
                return ResourceManager.GetString("Text_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Text_Options {
            get {
                return ResourceManager.GetString("Text_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Text_Requirements {
            get {
                return ResourceManager.GetString("Text_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcommands.
        /// </summary>
        public static string Text_Subcommands {
            get {
                return ResourceManager.GetString("Text_Subcommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Text_Summary {
            get {
                return ResourceManager.GetString("Text_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Text_Usage {
            get {
                return ResourceManager.GetString("Text_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Text_Variables {
            get {
                return ResourceManager.GetString("Text_Variables", resourceCulture);
            }
        }
    }
}
